### ISSUE TITLE
Mosquitto in swarm

### ISSUE THREAD

**Issue by shajek** [holgerimbery/docker_mosquitto#5]
Hello, thank you for your work. Can you instruct me how correctly do "swarm" with mosquitto and glusterfs ? I guess that gluster is needed for synchornization mosquitto configs and all of messages/retain messages. i see, that you use /mnt/glusterfs/etcetcetc ... but how can i reach that ? thank you for help

**Comment by holgerimbery** [comment]
Hello,
your welcome.

Basically, I followed the standard setup process mentioned on [glusterfs website](https://docs.gluster.org/en/latest/Quick-Start-Guide/Quickstart/#installing-glusterfs-a-quick-start-guide) and used a directory to share configuration files across the swarm.

I never used mosquitto on more than one worker nodes to create a HA setup.

If you want to have a mqtt broker HA setup you should consider [HiveMQ HA](https://www.hivemq.com/papers-download/Clustering_HiveMQ.pdf), or if you are looking only for redundacy and you don´t want to scale horizontally - you will find a solution here with [mosquitto-ha](https://github.com/roobytwo/mosquitto-HA).
